version: "3.0"

services:
  telegraf-1:
    image: telegraf:1.16.0
    restart: always
    container_name: telegraf-1
    hostname: telegraf-1
    ports:
      - 9273:9273
    volumes:
      - ./telegraf-1/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegraf-1/telegraf.d/:/etc/telegraf/telegraf.d/
    command: telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
  telegraf-2:
    image: telegraf:1.16.0
    restart: always
    container_name: telegraf-2
    hostname: telegraf-2
    ports:
      - 9274:9274
    volumes:
      - ./telegraf-2/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegraf-2/telegraf.d/:/etc/telegraf/telegraf.d/
    command: telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
  python-exporter:
    image: python:3.8.5-alpine3.12
    restart: always
    container_name: python-exporter
    hostname: python-exporter
    ports:
      - 9275:8000
    volumes:
      - ./python/metrics:/metrics
    command: python -m http.server
